# Generated by Django 3.2.6 on 2021-08-10 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('madeDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Introduction', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CircleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('signupDate', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('circleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_info.circle')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_signup.user')),
            ],
        ),
    ]
