# Generated by Django 3.2.6 on 2021-08-10 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_signup', '0001_initial'),
        ('b_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('recruitStartDate', models.DateTimeField(blank=True, null=True)),
                ('recruitEndDate', models.DateTimeField(blank=True, null=True)),
                ('howManyMember', models.IntegerField(blank=True, default=0)),
                ('keyword', models.CharField(blank=True, max_length=50)),
                ('detailContent', models.TextField()),
                ('img', models.CharField(blank=True, max_length=100)),
                ('writeDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('view', models.IntegerField(default=0)),
                ('circleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_info.circle')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_signup.user')),
            ],
        ),
    ]
