# Generated by Django 3.2.6 on 2021-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_bulletin', '0003_alter_promotionpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionpost',
            name='recruitEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionpost',
            name='recruitStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
