# Generated by Django 3.2.6 on 2021-08-10 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ID', models.CharField(max_length=20, unique=True)),
                ('nickName', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('passWord', models.CharField(max_length=20)),
                ('enterYear', models.DateField(blank=True, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('school', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('isAuth', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('registDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('profileImg', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_art', models.BooleanField(default=False)),
                ('volunteer_social', models.BooleanField(default=False)),
                ('academic_cultivative', models.BooleanField(default=False)),
                ('startup_employment', models.BooleanField(default=False)),
                ('language', models.BooleanField(default=False)),
                ('physics', models.BooleanField(default=False)),
                ('coding', models.BooleanField(default=False)),
                ('study', models.BooleanField(default=False)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_signup.user')),
            ],
        ),
    ]
