# Generated by Django 3.2.6 on 2021-08-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_bulletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=200)),
                ('temporary', models.BooleanField(default=False)),
                ('promotionPostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_bulletin.promotionpost')),
            ],
        ),
    ]
