# Generated by Django 3.2.6 on 2021-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_apply', '0003_alter_apply_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
