# Generated by Django 3.2.6 on 2021-08-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b_bulletin', '0004_auto_20210813_2214'),
        ('b_apply', '0004_apply_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='question',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('promotionPostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_bulletin.promotionpost')),
            ],
        ),
    ]
