# Generated by Django 3.2.6 on 2021-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_apply', '0005_auto_20210813_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='questionID',
            field=models.IntegerField(null=True),
        ),
    ]
